### PR TITLE
Improve imports

### PR DESCRIPTION
**Pull request by fcollonval**
Fix some imports and set `jupyterlab-markup` as dependency

I had to remove the auto disabling core factory. If it is set, the notebook editor is not available any more. I don't know why.

Sounds like a bug in JLab because if I manually set `jupyter labextension disable "@jupyterlab/notebook-extension:factory"`, everything works fine.

### CODE REVIEW

**Comment by agoose77** [comment]
Thanks for cleaning these up, also needed to be done.

I'm not sure on the protocol for adding dependencies in the Python package, which is why I left it out until now. My gut instinct is that we should assume if the user is installing one extension via PyPI, they want both via PyPI, so I'm on board with the suggestion.

**Comment by agoose77** [comment]
Let's add an install for `jupyterlab` too so that we have `jlpm`. I'd still like to use a PEP517 builder with isolation for the package build stage.

**Comment by agoose77** [comment]
LGTM :)

**Comment by fcollonval** [comment]
Thanks I'm trying it on binder as I still have a doubt about the `disabledExtensions` setup in `package.json`. If it works, I'll then merge.

**Comment by fcollonval** [comment]
I confirm that if `disabledExtensions` is set, it breaks JupyterLab. So I remove it. I'll merge as the error is unrelated.

**Pull request merged**
